version: "3.9"
   
services:
  db:
    image: postgres:13
    container_name: mathesar_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB-mathesar_django}
      - POSTGRES_USER=${POSTGRES_USER-mathesar}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD-mathesar}
    ports:
      - "5432:5432"
    volumes:
      - ./.volumes:/var/lib/postgresql/data
  service:
    build:
      context: .
      # Change this to Dockerfile.integ-tests to be able to run e2e integ tests
      dockerfile: Dockerfile
    container_name: mathesar_service
    environment:
      - MODE=${MODE-PRODUCTION}
    command: dockerize -wait tcp://mathesar_db:5432 -timeout 30s ./run.sh
    volumes:
      - .:/code/
      - ui_node_modules:/code/mathesar_ui/node_modules/
    ports:
      - "8000:8000"
      - "3000:3000"
      - "6006:6006"
    depends_on:
      - db

volumes:
  ui_node_modules:
